---
title: "Shannon like R Markdown Sorry"
author: "Shannon Houser"
date: "4/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggrepel)
library(usethis)
library(usmap)
library(sf)
library(lubridate)
library(gganimate)
library(gifski)
```

```{r}
USStates <- read_csv("../data/Social Distancing - States.csv")
```

```{r}
is_outlier <- function(x) {
  return(x <= quantile(x, 0.25) - 1.5 * IQR(x) | x >= quantile(x, 0.75) + 1.5 * IQR(x))
}
```


```{r}
USStates %>%
  pivot_longer(cols = c("retail_recreation",	"grocery_pharmacy",	"parks",	
                        "transit_stations",	"workplaces",	"residential"),
               names_to = "type") %>%
  group_by(type) %>%
  mutate(outlier = ifelse(is_outlier(value), value, as.numeric(NA)),
         high_low = case_when(
           !is.na(outlier) & outlier > mean(value) ~ "High",
           !is.na(outlier) & outlier < mean(value) ~ "Low",
           TRUE ~ as.character(NA))) %>%
  ggplot() +
  geom_boxplot(aes(x = reorder(type, -value), y = value/100)) +
  geom_text_repel(aes(x = reorder(type, -value), y = value/100,
                      label = ifelse(!is.na(outlier), paste0(state, ": ", outlier, "%"), ""),
                      color = high_low), size = 3, fontface = "bold") +
  scale_x_discrete(labels = c("Residential", "Parks", "Grocery/Pharmacy", "Workplaces", "Retail/Recreation", "Transit Stations")) +
  scale_y_continuous(labels = scales::percent) +
  scale_color_manual(values = c("red", "blue")) +
  guides(color = F) +
  labs(title = "United States Mobility Trends",
       subtitle = paste0("as of ", USStates$date),
       x = NULL,
       y = "%Change in Mobility",
       caption = "Data courtesy of Google")
```

```{r}
county_covid <- read_csv("../data/covid_combined_usafacts.csv")
```

```{r}
state_covid <- county_covid %>% 
  group_by(State, Type, Governor, stateFIPS) %>% 
  summarise("Population" = sum(population),
            "1/22/20" = sum(`1/22/2020`),
            "1/23/20" = sum(`1/23/2020`),
            "1/24/20" = sum(`1/24/2020`),
            "1/25/20" = sum(`1/25/2020`),
            "1/26/20" = sum(`1/26/2020`),
            "1/27/20" = sum(`1/27/2020`),
            "1/28/20" = sum(`1/28/2020`),
            "1/29/20" = sum(`1/29/2020`),
            "1/30/20" = sum(`1/30/2020`),
            "1/31/20" = sum(`1/31/2020`),
            "2/1/20" = sum(`2/1/2020`),
            "2/2/20" = sum(`2/2/2020`),
            "2/3/20" = sum(`2/3/2020`),
            "2/4/20" = sum(`2/4/2020`),
            "2/5/20" = sum(`2/5/2020`),
            "2/6/20" = sum(`2/6/2020`),
            "2/7/20" = sum(`2/7/2020`),
            "2/8/20" = sum(`2/8/2020`),
            "2/9/20" = sum(`2/9/2020`),
            "2/10/20" = sum(`2/10/2020`),
            "2/11/20" = sum(`2/11/2020`),
            "2/12/20" = sum(`2/12/2020`),
            "2/13/20" = sum(`2/13/2020`),
            "2/14/20" = sum(`2/14/2020`),
            "2/15/20" = sum(`2/15/2020`),
            "2/16/20" = sum(`2/16/2020`),
            "2/17/20" = sum(`2/17/2020`),
            "2/18/20" = sum(`2/18/2020`),
            "2/19/20" = sum(`2/19/2020`),
            "2/20/20" = sum(`2/20/2020`),
            "2/21/20" = sum(`2/21/2020`),
            "2/22/20" = sum(`2/22/2020`),
            "2/23/20" = sum(`2/23/2020`),
            "2/24/20" = sum(`2/24/2020`),
            "2/25/20" = sum(`2/25/2020`),
            "2/26/20" = sum(`2/26/2020`),
            "2/27/20" = sum(`2/27/2020`),
            "2/28/20" = sum(`2/28/2020`),
            "2/29/20" = sum(`2/29/2020`),
            "3/1/20" = sum(`3/1/2020`),
            "3/2/20" = sum(`3/2/2020`),
            "3/3/20" = sum(`3/3/2020`),
            "3/4/20" = sum(`3/4/2020`),
            "3/5/20" = sum(`3/5/2020`),
            "3/6/20" = sum(`3/6/2020`),
            "3/7/20" = sum(`3/7/2020`),
            "3/8/20" = sum(`3/8/2020`),
            "3/9/20" = sum(`3/9/2020`),
            "3/10/20" = sum(`3/10/2020`),
            "3/11/20" = sum(`3/11/2020`),
            "3/12/20" = sum(`3/12/2020`),
            "3/13/20" = sum(`3/13/2020`),
            "3/14/20" = sum(`3/14/2020`),
            "3/15/20" = sum(`3/15/2020`),
            "3/16/20" = sum(`3/16/2020`),
            "3/17/20" = sum(`3/17/2020`),
            "3/18/20" = sum(`3/18/2020`),
            "3/19/20" = sum(`3/19/2020`),
            "3/20/20" = sum(`3/20/2020`),
            "3/21/20" = sum(`3/21/2020`),
            "3/22/20" = sum(`3/22/2020`),
            "3/23/20" = sum(`3/23/2020`),
            "3/24/20" = sum(`3/24/2020`),
            "3/25/20" = sum(`3/25/2020`),
            "3/26/20" = sum(`3/26/2020`),
            "3/27/20" = sum(`3/27/2020`),
            "3/28/20" = sum(`3/28/2020`),
            "3/29/20" = sum(`3/29/2020`),
            "3/30/20" = sum(`3/30/2020`),
            "3/31/20" = sum(`3/31/2020`),
            "4/1/20" = sum(`4/1/2020`),
            "4/2/20" = sum(`4/2/2020`),
            "4/3/20" = sum(`4/3/2020`),
            "4/4/20" = sum(`4/4/2020`),
            "4/5/20" = sum(`4/5/2020`),
            "4/6/20" = sum(`4/6/2020`),
            "4/7/20" = sum(`4/7/2020`),
            "4/8/20" = sum(`4/8/2020`))
         
```

```{r}
state_covid <- state_covid %>% 
  rename(state = State,
         type = Type,
         governor = Governor,
         fips = stateFIPS,
         population = Population)
```

```{r}
state_covid_confirmed <- state_covid %>% 
  filter(type == "Confirmed")

state_covid_dead <- state_covid %>% 
  filter(type == "Deaths")

state_covid_dead %>% 
  group_by(governor) %>% 
  summarise(rep_dem = (sum(`4/8/20`)/sum(population)))

state_covid_confirmed <- state_covid_confirmed %>% 
  mutate(per_100k = (sum(`4/8/20`)/population)*100000) %>% 
  arrange(desc(per_100k)) %>% 
  ungroup()

state_covid_dead <- state_covid_dead %>% 
  mutate(per_100k = (sum(`4/8/20`)/population)*100000) %>% 
  arrange(desc(per_100k)) %>% 
  ungroup()
```

## Starting Fresh 

```{r}
plot_usmap(data = USStates, values = "retail_recreation")+
  scale_fill_gradient(low = "#cb181d", high = "#fff5f0", na.value = "grey50")
```

```{r}
plot_usmap(data = USStates, values = "grocery_pharmacy")+
  scale_fill_gradient(low = "#cb181d", high = "#fff5f0", na.value = "grey50")
```

```{r}
plot_usmap(data = USStates, values = "parks", labels = TRUE)+
  scale_fill_steps2(
  low = "#b2182b",
  mid = "white",
  high = "blue",
  midpoint = 0)
```

```{r}
plot_usmap(data = USStates, values = "transit_stations", labels = TRUE)+
  scale_fill_gradient(low = "#cb181d", high = "#fff5f0", na.value = "grey50")
```

```{r}
plot_usmap(data = USStates, values = "workplaces", labels = TRUE)+
  scale_fill_gradient(low = "#cb181d", high = "#fff5f0", na.value = "grey50")
```

```{r}
plot_usmap(data = USStates, values = "residential", labels = TRUE)+
  scale_fill_gradient(low = "#cb181d", high = "#fff5f0", na.value = "grey50")
```

```{r}
State_Action <- read_csv("../data/Social Distancing - State Actions.csv")%>%
  mutate("date of 1st Case" = as.Date("date of 1st Case", format = "%m/%d/%y"),
         "date of 1st Death" = as.Date("date of 1st Death", format = "%m/%d/%y"),
         "date of Stay at Home Order" = as.Date("date of Stay at Home Order", format = "%m/%d/%y"))
```

```{r}
USStates <- USStates %>% 
  mutate(date.of.1st.case = as.Date(date.of.1st.case, format = "%m/%d/%y"),
         date.of.1st.death = as.Date(date.of.1st.death, format = "%m/%d/%y"),
         date.of.stay.at.home.order = as.Date(date.of.stay.at.home.order, format = "%m/%d/%y"),
         state.mandated.school.closures = as.Date(state.mandated.school.closures, format = "%m/%d/%y"),
         emergency.declaration = as.Date(emergency.declaration, format = "%m/%d/%y"))

str(USStates)
```


```{r}
USStates <- USStates %>% 
  mutate(resp_home = date.of.stay.at.home.order - date.of.1st.case,
         resp_school = state.mandated.school.closures - date.of.1st.case,
         resp_emer = emergency.declaration - date.of.1st.case)

USStates %>% 
  ggplot(aes(x = date.of.1st.case, y = resp_home))+
  geom_point()

USStates %>% 
  ggplot(aes(x = date.of.1st.case, y = date.of.stay.at.home.order))+
  geom_point()

USStates %>% 
  ggplot(aes(x = date.of.1st.case, y = resp_school))+
  geom_point()

USStates %>% 
  ggplot(aes(x = date.of.1st.case, y = resp_emer))+
  geom_point()
# Roughly linear relationship between 1st case date and response times
```

```{r}
USStates %>% 
  mutate(parks_bin = ifelse(parks >0, "pos", "neg"))

USStates %>% 
  mutate(parks_bin = ifelse(parks >0, "pos", "neg")) %>% 
  group_by(parks_bin) %>% 
  filter(resp_home != is.na(resp_home)) %>% 
  summarise(mean(resp_home))

USStates %>% 
  mutate(parks_bin = ifelse(parks >0, "pos", "neg")) %>% 
  group_by(parks_bin) %>% 
  filter(resp_school != is.na(resp_school)) %>% 
  summarise(mean(resp_school))

USStates %>% 
  mutate(parks_bin = ifelse(parks >0, "pos", "neg")) %>% 
  group_by(parks_bin) %>% 
  filter(resp_emer != is.na(resp_emer)) %>% 
  summarise(mean(resp_emer))
```

```{r}
  state_covid_confirmed[ , 6:83] <- lapply(state_covid_confirmed[ , 6:83], as.Date, origin="1970-01-01")

str(state_covid_confirmed)
```
```{r}
state_covid_confirmed %>% 
  ggplot(aes(x = col(6:83), y = ))
```

